[package]
name = "soducant-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
soducant-core = {path = "../soducant-core"}
wasm-bindgen = "0.2"
getrandom = {version = "0.3.4", features = ["wasm_js"]}

[profile.release]
opt-level=3
lto="fat"
